UPDATE `exercises` SET `slug` = 'bench_press' WHERE `source` = 'preset' AND `name` = 'ベンチプレス' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'incline_bench_press' WHERE `source` = 'preset' AND `name` = 'インクラインベンチプレス' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'decline_bench_press' WHERE `source` = 'preset' AND `name` = 'デクラインベンチプレス' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'dumbbell_fly' WHERE `source` = 'preset' AND `name` = 'ダンベルフライ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'incline_dumbbell_fly' WHERE `source` = 'preset' AND `name` = 'インクラインダンベルフライ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'cable_crossover' WHERE `source` = 'preset' AND `name` = 'ケーブルクロスオーバー' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'chest_press_machine' WHERE `source` = 'preset' AND `name` = 'チェストプレス（マシン）' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'push_up' WHERE `source` = 'preset' AND `name` = 'プッシュアップ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'barbell_shoulder_press' WHERE `source` = 'preset' AND `name` = 'バーベルショルダープレス' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'dumbbell_shoulder_press' WHERE `source` = 'preset' AND `name` = 'ダンベルショルダープレス' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'side_raise' WHERE `source` = 'preset' AND `name` = 'サイドレイズ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'front_raise' WHERE `source` = 'preset' AND `name` = 'フロントレイズ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'rear_delt_fly' WHERE `source` = 'preset' AND `name` = 'リアデルトフライ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'face_pull' WHERE `source` = 'preset' AND `name` = 'フェイスプル' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'arnold_press' WHERE `source` = 'preset' AND `name` = 'アーノルドプレス' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'barbell_curl' WHERE `source` = 'preset' AND `name` = 'バーベルカール' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'dumbbell_curl' WHERE `source` = 'preset' AND `name` = 'ダンベルカール' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'hammer_curl' WHERE `source` = 'preset' AND `name` = 'ハンマーカール' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'preacher_curl' WHERE `source` = 'preset' AND `name` = 'プリーチャーカール' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'triceps_pushdown' WHERE `source` = 'preset' AND `name` = 'トライセプスプレスダウン' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'triceps_extension' WHERE `source` = 'preset' AND `name` = 'トライセプスエクステンション' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'french_press' WHERE `source` = 'preset' AND `name` = 'フレンチプレス' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'dips' WHERE `source` = 'preset' AND `name` = 'ディップス' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'plank' WHERE `source` = 'preset' AND `name` = 'プランク' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'side_plank' WHERE `source` = 'preset' AND `name` = 'サイドプランク' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'crunch' WHERE `source` = 'preset' AND `name` = 'クランチ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'leg_raise' WHERE `source` = 'preset' AND `name` = 'レッグレイズ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'russian_twist' WHERE `source` = 'preset' AND `name` = 'ロシアンツイスト' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'ab_wheel_rollout' WHERE `source` = 'preset' AND `name` = 'アブローラー' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'bicycle_crunch' WHERE `source` = 'preset' AND `name` = 'バイシクルクランチ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'deadlift' WHERE `source` = 'preset' AND `name` = 'デッドリフト' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'lat_pulldown' WHERE `source` = 'preset' AND `name` = 'ラットプルダウン' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'seated_cable_row' WHERE `source` = 'preset' AND `name` = 'シーテッドケーブルロウ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'barbell_row' WHERE `source` = 'preset' AND `name` = 'バーベルロウ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'dumbbell_one_arm_row' WHERE `source` = 'preset' AND `name` = 'ダンベルワンハンドロウ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'chin_up' WHERE `source` = 'preset' AND `name` = 'チンニング（懸垂）' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'pull_up' WHERE `source` = 'preset' AND `name` = 'プルアップ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'high_row' WHERE `source` = 'preset' AND `name` = 'ハイロウ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'back_extension' WHERE `source` = 'preset' AND `name` = 'バックエクステンション' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'running' WHERE `source` = 'preset' AND `name` = 'ランニング' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'walking' WHERE `source` = 'preset' AND `name` = 'ウォーキング' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'cycling' WHERE `source` = 'preset' AND `name` = 'サイクリング' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'rowing_ergometer' WHERE `source` = 'preset' AND `name` = 'ロウイング（エルゴ）' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'jump_rope' WHERE `source` = 'preset' AND `name` = '縄跳び' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'burpee' WHERE `source` = 'preset' AND `name` = 'バーピー' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'squat' WHERE `source` = 'preset' AND `name` = 'スクワット' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'front_squat' WHERE `source` = 'preset' AND `name` = 'フロントスクワット' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'leg_press' WHERE `source` = 'preset' AND `name` = 'レッグプレス' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'romanian_deadlift' WHERE `source` = 'preset' AND `name` = 'ルーマニアンデッドリフト' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'lunge' WHERE `source` = 'preset' AND `name` = 'ランジ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'bulgarian_split_squat' WHERE `source` = 'preset' AND `name` = 'ブルガリアンスプリットスクワット' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'leg_curl' WHERE `source` = 'preset' AND `name` = 'レッグカール' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'leg_extension' WHERE `source` = 'preset' AND `name` = 'レッグエクステンション' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'calf_raise' WHERE `source` = 'preset' AND `name` = 'カーフレイズ' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'goblet_squat' WHERE `source` = 'preset' AND `name` = 'ゴブレットスクワット' AND `slug` IS NULL;--> statement-breakpoint
UPDATE `exercises` SET `slug` = 'hip_thrust' WHERE `source` = 'preset' AND `name` = 'ヒップスラスト' AND `slug` IS NULL;
