import { db } from './client';
import { exercises } from './schema';
import { eq } from 'drizzle-orm';
import type { ExerciseCategory, MeasurementType } from '@/lib/exercises/constants';

type PresetExercise = {
  slug: string;
  name: string;
  category: ExerciseCategory;
  measurementType: MeasurementType;
};

export const PRESET_EXERCISES: PresetExercise[] = [
  // 胸
  { slug: 'bench_press', name: 'ベンチプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'incline_bench_press', name: 'インクラインベンチプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'decline_bench_press', name: 'デクラインベンチプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'dumbbell_fly', name: 'ダンベルフライ', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'incline_dumbbell_fly', name: 'インクラインダンベルフライ', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'cable_crossover', name: 'ケーブルクロスオーバー', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'chest_press_machine', name: 'チェストプレス（マシン）', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'push_up', name: 'プッシュアップ', category: 'chest', measurementType: 'reps' },
  { slug: 'smith_bench_press', name: 'スミスマシンベンチプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'close_grip_bench_press', name: 'クローズグリップベンチプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'reverse_grip_bench_press', name: 'リバースグリップベンチプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'dumbbell_bench_press', name: 'ダンベルベンチプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'incline_dumbbell_press', name: 'インクラインダンベルプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'decline_dumbbell_press', name: 'デクラインダンベルプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'decline_dumbbell_fly', name: 'デクラインダンベルフライ', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'pec_deck', name: 'ペックデック（バタフライマシン）', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'low_cable_fly', name: 'ローケーブルフライ', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'high_cable_fly', name: 'ハイケーブルフライ', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'svend_press', name: 'スベンドプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'floor_press', name: 'フロアプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'resistance_band_chest_press', name: 'バンドチェストプレス', category: 'chest', measurementType: 'reps' },
  { slug: 'incline_push_up', name: 'インクラインプッシュアップ', category: 'chest', measurementType: 'reps' },
  { slug: 'decline_push_up', name: 'デクラインプッシュアップ', category: 'chest', measurementType: 'reps' },
  { slug: 'diamond_push_up', name: 'ダイヤモンドプッシュアップ', category: 'chest', measurementType: 'reps' },
  { slug: 'wide_push_up', name: 'ワイドプッシュアップ', category: 'chest', measurementType: 'reps' },
  { slug: 'kneeling_push_up', name: '膝つきプッシュアップ', category: 'chest', measurementType: 'reps' },
  { slug: 'weighted_push_up', name: '加重プッシュアップ', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'single_arm_dumbbell_press', name: 'シングルアームダンベルプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'guillotine_press', name: 'ギロチンプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'floor_fly', name: 'フロアフライ', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'incline_smith_press', name: 'インクラインスミスプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'decline_smith_press', name: 'デクラインスミスプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'single_arm_cable_fly', name: 'シングルアームケーブルフライ', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'decline_cable_fly', name: 'デクラインケーブルフライ', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'incline_cable_fly', name: 'インクラインケーブルフライ', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'dumbbell_pullover', name: 'ダンベルプルオーバー', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'spoto_press', name: 'スポトプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'board_press', name: 'ボードプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'one_arm_push_up', name: '片腕プッシュアップ', category: 'chest', measurementType: 'reps' },
  { slug: 'clap_push_up', name: 'クラッププッシュアップ', category: 'chest', measurementType: 'reps' },
  { slug: 'hindu_push_up', name: 'ヒンズープッシュアップ', category: 'chest', measurementType: 'reps' },
  { slug: 'archer_push_up', name: 'アーチャープッシュアップ', category: 'chest', measurementType: 'reps' },
  { slug: 'machine_incline_press', name: 'マシンインクラインプレス', category: 'chest', measurementType: 'weight_reps' },
  { slug: 'standing_cable_chest_press', name: 'スタンディングケーブルチェストプレス', category: 'chest', measurementType: 'weight_reps' },
  // 肩
  { slug: 'barbell_shoulder_press', name: 'バーベルショルダープレス', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'dumbbell_shoulder_press', name: 'ダンベルショルダープレス', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'side_raise', name: 'サイドレイズ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'front_raise', name: 'フロントレイズ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'rear_delt_fly', name: 'リアデルトフライ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'face_pull', name: 'フェイスプル', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'arnold_press', name: 'アーノルドプレス', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'seated_barbell_shoulder_press', name: 'シーテッドバーベルショルダープレス', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'single_arm_dumbbell_shoulder_press', name: 'シングルアームダンベルショルダープレス', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'plate_front_raise', name: 'プレートフロントレイズ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'lu_raise', name: 'ルーレイズ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'y_raise', name: 'Yレイズ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'cuban_press', name: 'キューバンプレス', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'scott_press', name: 'スコットプレス', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'landmine_lateral_raise', name: 'ランドミンサイドレイズ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'band_pull_apart', name: 'バンドプルアパート', category: 'shoulder', measurementType: 'reps' },
  { slug: 'landmine_press', name: 'ランドミンプレス', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'upright_row', name: 'アップライトロウ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'cable_upright_row', name: 'ケーブルアップライトロウ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'shrug', name: 'シュラッグ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'dumbbell_shrug', name: 'ダンベルシュラッグ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'behind_neck_press', name: 'ビハインドネックプレス', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'reverse_pec_deck', name: 'リアデルトマシン', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'cable_rear_delt_fly', name: 'ケーブルリアデルトフライ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'kettlebell_shoulder_press', name: 'ケトルベルショルダープレス', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'push_press', name: 'プッシュプレス', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'pike_push_up', name: 'パイクプッシュアップ', category: 'shoulder', measurementType: 'reps' },
  { slug: 'handstand_push_up', name: 'ハンドスタンドプッシュアップ', category: 'shoulder', measurementType: 'reps' },
  { slug: 'machine_shoulder_press', name: 'マシンショルダープレス', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'cable_lateral_raise', name: 'ケーブルサイドレイズ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'cable_front_raise', name: 'ケーブルフロントレイズ', category: 'shoulder', measurementType: 'weight_reps' },
  { slug: 'trap_bar_shrug', name: 'トラップバーシュラッグ', category: 'shoulder', measurementType: 'weight_reps' },
  // 腕
  { slug: 'barbell_curl', name: 'バーベルカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'dumbbell_curl', name: 'ダンベルカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'hammer_curl', name: 'ハンマーカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'preacher_curl', name: 'プリーチャーカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'triceps_pushdown', name: 'トライセプスプレスダウン', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'triceps_extension', name: 'トライセプスエクステンション', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'french_press', name: 'フレンチプレス', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'dips', name: 'ディップス', category: 'arm', measurementType: 'reps' },
  { slug: 'weighted_dips', name: '加重ディップス', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'ez_bar_curl', name: 'EZバーカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'cable_curl', name: 'ケーブルカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'concentration_curl', name: 'コンセントレーションカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'incline_dumbbell_curl', name: 'インクラインダンベルカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'spider_curl', name: 'スパイダーカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'zottman_curl', name: 'ザットマンカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'drag_curl', name: 'ドラッグカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'reverse_curl', name: 'リバースカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'cable_hammer_curl', name: 'ケーブルハンマーカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'overhead_cable_extension', name: 'オーバーヘッドケーブルエクステンション', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'bench_dip', name: 'ベンチディップス', category: 'arm', measurementType: 'reps' },
  { slug: 'weighted_bench_dip', name: '加重ベンチディップス', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'wrist_curl', name: 'リストカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'reverse_wrist_curl', name: 'リバースリストカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'farmers_walk', name: 'ファーマーズウォーク', category: 'arm', measurementType: 'weight_time' },
  { slug: 'preacher_hammer_curl', name: 'プリーチャーハンマーカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'machine_preacher_curl', name: 'マシンプリーチャーカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'cable_rope_hammer_curl', name: 'ケーブルロープハンマーカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'curl_21s', name: '21カール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'waiter_curl', name: 'ウェイターカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'cross_body_hammer_curl', name: 'クロスボディハンマーカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'single_arm_dumbbell_curl', name: 'シングルアームダンベルカール', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'band_curl', name: 'バンドカール', category: 'arm', measurementType: 'reps' },
  { slug: 'single_arm_triceps_pushdown', name: 'シングルアームトライセプスプレスダウン', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'rope_pushdown', name: 'ロープトライセプスプレスダウン', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'v_bar_pushdown', name: 'Vバートライセプスプレスダウン', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'lying_triceps_extension', name: 'ライイングトライセプスエクステンション', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'one_arm_triceps_extension', name: 'ワンアームトライセプスエクステンション', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'band_triceps_extension', name: 'バンドトライセプスエクステンション', category: 'arm', measurementType: 'reps' },
  { slug: 'wrist_roller', name: 'リストローラー', category: 'arm', measurementType: 'weight_time' },
  { slug: 'plate_pinch_grip', name: 'プレートピンチグリップ', category: 'arm', measurementType: 'weight_time' },
  { slug: 'triceps_kickback', name: 'トライセプスキックバック', category: 'arm', measurementType: 'weight_reps' },
  { slug: 'assisted_dip_machine', name: 'アシステッドディップマシン', category: 'arm', measurementType: 'weight_reps' },
  // 体幹
  { slug: 'plank', name: 'プランク', category: 'core', measurementType: 'time' },
  { slug: 'side_plank', name: 'サイドプランク', category: 'core', measurementType: 'time' },
  { slug: 'mountain_climber', name: 'マウンテンクライマー', category: 'core', measurementType: 'reps' },
  { slug: 'dead_bug', name: 'デッドバグ', category: 'core', measurementType: 'reps' },
  { slug: 'bird_dog', name: 'バードドッグ', category: 'core', measurementType: 'reps' },
  { slug: 'hollow_body_hold', name: 'ホローボディホールド', category: 'core', measurementType: 'time' },
  { slug: 'superman', name: 'スーパーマン', category: 'core', measurementType: 'reps' },
  { slug: 'pallof_press', name: 'パロフプレス', category: 'core', measurementType: 'weight_reps' },
  { slug: 'plank_shoulder_tap', name: 'プランクショルダータップ', category: 'core', measurementType: 'reps' },
  { slug: 'side_plank_rotation', name: 'サイドプランクロテーション', category: 'core', measurementType: 'reps' },
  { slug: 'stir_the_pot', name: 'スターザポット', category: 'core', measurementType: 'time' },
  { slug: 'hollow_rock', name: 'ホローロック', category: 'core', measurementType: 'reps' },
  { slug: 'l_sit', name: 'Lシット', category: 'core', measurementType: 'time' },
  { slug: 'weighted_plank', name: '加重プランク', category: 'core', measurementType: 'weight_time' },
  { slug: 'reverse_plank', name: 'リバースプランク', category: 'core', measurementType: 'time' },
  // 腹筋
  { slug: 'crunch', name: 'クランチ', category: 'abs', measurementType: 'reps' },
  { slug: 'leg_raise', name: 'レッグレイズ', category: 'abs', measurementType: 'reps' },
  { slug: 'russian_twist', name: 'ロシアンツイスト', category: 'abs', measurementType: 'reps' },
  { slug: 'ab_wheel_rollout', name: 'アブローラー', category: 'abs', measurementType: 'reps' },
  { slug: 'bicycle_crunch', name: 'バイシクルクランチ', category: 'abs', measurementType: 'reps' },
  { slug: 'hanging_leg_raise', name: 'ハンギングレッグレイズ', category: 'abs', measurementType: 'reps' },
  { slug: 'captains_chair_raise', name: 'キャプテンズチェアレイズ', category: 'abs', measurementType: 'reps' },
  { slug: 'v_up', name: 'Vアップ', category: 'abs', measurementType: 'reps' },
  { slug: 'toe_touch', name: 'トゥタッチ', category: 'abs', measurementType: 'reps' },
  { slug: 'flutter_kick', name: 'フラッターキック', category: 'abs', measurementType: 'reps' },
  { slug: 'cable_crunch', name: 'ケーブルクランチ', category: 'abs', measurementType: 'weight_reps' },
  { slug: 'reverse_crunch', name: 'リバースクランチ', category: 'abs', measurementType: 'reps' },
  { slug: 'decline_crunch', name: 'デクラインクランチ', category: 'abs', measurementType: 'reps' },
  { slug: 'sit_up', name: 'シットアップ', category: 'abs', measurementType: 'reps' },
  { slug: 'weighted_sit_up', name: '加重シットアップ', category: 'abs', measurementType: 'weight_reps' },
  { slug: 'side_bend', name: 'サイドベンド', category: 'abs', measurementType: 'reps' },
  { slug: 'decline_sit_up', name: 'デクラインシットアップ', category: 'abs', measurementType: 'reps' },
  { slug: 'weighted_decline_sit_up', name: '加重デクラインシットアップ', category: 'abs', measurementType: 'weight_reps' },
  { slug: 'hanging_knee_raise', name: 'ハンギングニーレイズ', category: 'abs', measurementType: 'reps' },
  { slug: 'weighted_hanging_knee_raise', name: '加重ハンギングニーレイズ', category: 'abs', measurementType: 'weight_reps' },
  { slug: 'cable_woodchopper', name: 'ケーブルウッドチョッパー', category: 'abs', measurementType: 'weight_reps' },
  { slug: 'dragon_flag', name: 'ドラゴンフラッグ', category: 'abs', measurementType: 'reps' },
  { slug: 'jackknife_situp', name: 'ジャックナイフシットアップ', category: 'abs', measurementType: 'reps' },
  { slug: 'toes_to_bar', name: 'トゥーズトゥーバー', category: 'abs', measurementType: 'reps' },
  { slug: 'hanging_windshield_wiper', name: 'ハンギングワイパー', category: 'abs', measurementType: 'reps' },
  { slug: 'knee_to_elbow_plank', name: 'ニートゥエルボープランク', category: 'abs', measurementType: 'reps' },
  { slug: 'stability_ball_crunch', name: 'バランスボールクランチ', category: 'abs', measurementType: 'reps' },
  { slug: 'landmine_twist', name: 'ランドミンツイスト', category: 'abs', measurementType: 'weight_reps' },
  // 背中
  { slug: 'deadlift', name: 'デッドリフト', category: 'back', measurementType: 'weight_reps' },
  { slug: 'lat_pulldown', name: 'ラットプルダウン', category: 'back', measurementType: 'weight_reps' },
  { slug: 'seated_cable_row', name: 'シーテッドケーブルロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'barbell_row', name: 'バーベルロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'dumbbell_one_arm_row', name: 'ダンベルワンハンドロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'chin_up', name: 'チンニング（懸垂）', category: 'back', measurementType: 'reps' },
  { slug: 'weighted_chin_up', name: '加重チンニング（加重懸垂）', category: 'back', measurementType: 'weight_reps' },
  { slug: 'pull_up', name: 'プルアップ（懸垂）', category: 'back', measurementType: 'reps' },
  { slug: 'weighted_pull_up', name: '加重プルアップ（加重懸垂）', category: 'back', measurementType: 'weight_reps' },
  { slug: 'high_row', name: 'ハイロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'back_extension', name: 'バックエクステンション', category: 'back', measurementType: 'reps' },
  { slug: 'weighted_back_extension', name: '加重バックエクステンション', category: 'back', measurementType: 'weight_reps' },
  { slug: 't_bar_row', name: 'Tバーロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'pendlay_row', name: 'ペンドレーロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'machine_row', name: 'マシンロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'cable_straight_arm_pulldown', name: 'ケーブルストレートアームプルダウン', category: 'back', measurementType: 'weight_reps' },
  { slug: 'close_grip_lat_pulldown', name: 'クローズグリップラットプルダウン', category: 'back', measurementType: 'weight_reps' },
  { slug: 'reverse_grip_lat_pulldown', name: 'リバースグリップラットプルダウン', category: 'back', measurementType: 'weight_reps' },
  { slug: 'single_arm_lat_pulldown', name: 'シングルアームラットプルダウン', category: 'back', measurementType: 'weight_reps' },
  { slug: 'rack_pull', name: 'ラックプル', category: 'back', measurementType: 'weight_reps' },
  { slug: 'sumo_deadlift', name: 'スモウデッドリフト', category: 'back', measurementType: 'weight_reps' },
  { slug: 'deficit_deadlift', name: 'デフィシットデッドリフト', category: 'back', measurementType: 'weight_reps' },
  { slug: 'good_morning', name: 'グッドモーニング', category: 'back', measurementType: 'weight_reps' },
  { slug: 'inverted_row', name: 'インバーテッドロウ', category: 'back', measurementType: 'reps' },
  { slug: 'renegade_row', name: 'レネゲードロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'meadows_row', name: 'メドウズロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'landmine_row', name: 'ランドミンロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'kroc_row', name: 'クロックロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'chest_supported_row', name: 'チェストサポートロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'seal_row', name: 'シールロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'wide_grip_pull_up', name: 'ワイドグリップ懸垂', category: 'back', measurementType: 'reps' },
  { slug: 'close_grip_pull_up', name: 'クローズグリップ懸垂', category: 'back', measurementType: 'reps' },
  { slug: 'neutral_grip_pull_up', name: 'ニュートラルグリップ懸垂', category: 'back', measurementType: 'reps' },
  { slug: 'weighted_neutral_grip_pull_up', name: '加重ニュートラルグリップ懸垂', category: 'back', measurementType: 'weight_reps' },
  { slug: 'assisted_pull_up', name: 'アシストプルアップ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'negative_pull_up', name: 'ネガティブ懸垂', category: 'back', measurementType: 'reps' },
  { slug: 'single_arm_cable_row', name: 'シングルアームケーブルロウ', category: 'back', measurementType: 'weight_reps' },
  { slug: 'snatch_grip_deadlift', name: 'スナッチグリップデッドリフト', category: 'back', measurementType: 'weight_reps' },
  { slug: 'trap_bar_deadlift', name: 'トラップバーデッドリフト', category: 'back', measurementType: 'weight_reps' },
  { slug: 'stiff_leg_deadlift', name: 'スティッフレッグデッドリフト', category: 'back', measurementType: 'weight_reps' },
  { slug: 'banded_deadlift', name: 'バンドデッドリフト', category: 'back', measurementType: 'reps' },
  { slug: 'muscle_up', name: 'マッスルアップ', category: 'back', measurementType: 'reps' },
  { slug: 'band_lat_pulldown', name: 'バンドラットプルダウン', category: 'back', measurementType: 'reps' },
  // 有酸素
  { slug: 'running', name: 'ランニング', category: 'cardio', measurementType: 'distance_time' },
  { slug: 'walking', name: 'ウォーキング', category: 'cardio', measurementType: 'distance_time' },
  { slug: 'cycling', name: 'サイクリング', category: 'cardio', measurementType: 'distance_time' },
  { slug: 'rowing_ergometer', name: 'ロウイング（エルゴ）', category: 'cardio', measurementType: 'distance_time' },
  { slug: 'jump_rope', name: '縄跳び', category: 'cardio', measurementType: 'time' },
  { slug: 'burpee', name: 'バーピー', category: 'cardio', measurementType: 'reps' },
  { slug: 'elliptical', name: 'エリプティカル（クロストレーナー）', category: 'cardio', measurementType: 'distance_time' },
  { slug: 'stair_climber', name: 'ステアクライマー', category: 'cardio', measurementType: 'time' },
  { slug: 'high_knees', name: 'ハイニー', category: 'cardio', measurementType: 'time' },
  { slug: 'battle_rope', name: 'バトルロープ', category: 'cardio', measurementType: 'time' },
  { slug: 'box_jump', name: 'ボックスジャンプ', category: 'cardio', measurementType: 'reps' },
  { slug: 'shuttle_run', name: 'シャトルラン', category: 'cardio', measurementType: 'distance_time' },
  { slug: 'swimming', name: '水泳', category: 'cardio', measurementType: 'distance_time' },
  { slug: 'hiit_circuit', name: 'HIITサーキット', category: 'cardio', measurementType: 'time' },
  { slug: 'assault_bike', name: 'アサルトバイク', category: 'cardio', measurementType: 'distance_time' },
  { slug: 'kettlebell_swing', name: 'ケトルベルスイング', category: 'cardio', measurementType: 'weight_reps' },
  { slug: 'sled_push', name: 'ソリ押し（プッシュスレッド）', category: 'cardio', measurementType: 'weight_time' },
  { slug: 'sprint_intervals', name: 'スプリントインターバル', category: 'cardio', measurementType: 'distance_time' },
  { slug: 'agility_ladder', name: 'アジリティラダー', category: 'cardio', measurementType: 'time' },
  { slug: 'jumping_jack', name: 'ジャンピングジャック', category: 'cardio', measurementType: 'time' },
  { slug: 'skater_jump', name: 'スケータージャンプ', category: 'cardio', measurementType: 'reps' },
  { slug: 'broad_jump', name: '立ち幅跳び', category: 'cardio', measurementType: 'reps' },
  { slug: 'tuck_jump', name: 'タックジャンプ', category: 'cardio', measurementType: 'reps' },
  { slug: 'rope_climb', name: 'ロープクライム', category: 'cardio', measurementType: 'reps' },
  { slug: 'double_unders', name: 'ダブルアンダー', category: 'cardio', measurementType: 'reps' },
  // 脚
  { slug: 'squat', name: 'スクワット', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'front_squat', name: 'フロントスクワット', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'leg_press', name: 'レッグプレス', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'romanian_deadlift', name: 'ルーマニアンデッドリフト', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'lunge', name: 'ランジ', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'bulgarian_split_squat', name: 'ブルガリアンスプリットスクワット', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'leg_curl', name: 'レッグカール', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'leg_extension', name: 'レッグエクステンション', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'calf_raise', name: 'カーフレイズ', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'goblet_squat', name: 'ゴブレットスクワット', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'hack_squat', name: 'ハックスクワット', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'smith_squat', name: 'スミスマシンスクワット', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'box_squat', name: 'ボックススクワット', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'sumo_squat', name: 'スモウスクワット', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'pistol_squat', name: 'ピストルスクワット', category: 'leg', measurementType: 'reps' },
  { slug: 'step_up', name: 'ステップアップ', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'walking_lunge', name: 'ウォーキングランジ', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'reverse_lunge', name: 'リバースランジ', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'lateral_lunge', name: 'サイドランジ', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'curtsy_lunge', name: 'カーツィランジ', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'seated_leg_curl', name: 'シーテッドレッグカール', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'seated_calf_raise', name: 'シーテッドカーフレイズ', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'donkey_calf_raise', name: 'ドンキーカーフレイズ', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'adductor_machine', name: 'アダクターマシン（内転筋マシン）', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'abductor_machine', name: 'アブダクターマシン（外転筋マシン）', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'sissy_squat', name: 'シシースクワット', category: 'leg', measurementType: 'reps' },
  { slug: 'weighted_sissy_squat', name: '加重シシースクワット', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'jump_squat', name: 'ジャンプスクワット', category: 'leg', measurementType: 'reps' },
  { slug: 'wall_sit', name: 'ウォールシット', category: 'leg', measurementType: 'time' },
  { slug: 'single_leg_deadlift', name: 'シングルレッグデッドリフト', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'zercher_squat', name: 'ザーチャースクワット', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'pin_squat', name: 'ピンスクワット', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'smith_lunge', name: 'スミスランジ', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'dumbbell_lunge', name: 'ダンベルランジ', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'barbell_lunge', name: 'バーベルランジ', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'overhead_squat', name: 'オーバーヘッドスクワット', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'cossack_squat', name: 'コサックスクワット', category: 'leg', measurementType: 'reps' },
  { slug: 'belt_squat', name: 'ベルトスクワット', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'leg_press_calf_raise', name: 'レッグプレスカーフレイズ', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'cable_hip_abduction', name: 'ケーブルヒップアブダクション', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'cable_hip_adduction', name: 'ケーブルヒップアダクション', category: 'leg', measurementType: 'weight_reps' },
  { slug: 'nordic_hamstring_curl', name: 'ノルディックハムストリングカール', category: 'leg', measurementType: 'reps' },
  { slug: 'glute_ham_raise', name: 'グルートハムレイズ', category: 'leg', measurementType: 'reps' },
  { slug: 'banded_squat', name: 'バンドスクワット', category: 'leg', measurementType: 'reps' },
  { slug: 'tibialis_raise', name: 'ティビアリスレイズ（すね上げ）', category: 'leg', measurementType: 'reps' },
  { slug: 'walking_calf_raise', name: 'ウォーキングカーフレイズ', category: 'leg', measurementType: 'reps' },
  // お尻
  { slug: 'hip_thrust', name: 'ヒップスラスト', category: 'glute', measurementType: 'weight_reps' },
  { slug: 'glute_bridge', name: 'グルートブリッジ', category: 'glute', measurementType: 'weight_reps' },
  { slug: 'cable_kickback', name: 'ケーブルキックバック', category: 'glute', measurementType: 'weight_reps' },
  { slug: 'donkey_kick', name: 'ドンキーキック', category: 'glute', measurementType: 'weight_reps' },
  { slug: 'fire_hydrant', name: 'ファイヤーハイドラント', category: 'glute', measurementType: 'weight_reps' },
  { slug: 'glute_kickback_machine', name: 'グルートキックバックマシン', category: 'glute', measurementType: 'weight_reps' },
  { slug: 'single_leg_hip_thrust', name: 'シングルレッグヒップスラスト', category: 'glute', measurementType: 'weight_reps' },
  { slug: 'cable_pull_through', name: 'ケーブルプルスルー', category: 'glute', measurementType: 'weight_reps' },
  { slug: 'reverse_hyperextension', name: 'リバースハイパーエクステンション', category: 'glute', measurementType: 'weight_reps' },
  { slug: 'barbell_glute_bridge', name: 'バーベルグルートブリッジ', category: 'glute', measurementType: 'weight_reps' },
  { slug: 'banded_glute_bridge', name: 'バンドグルートブリッジ', category: 'glute', measurementType: 'reps' },
  { slug: 'clamshell', name: 'クラムシェル', category: 'glute', measurementType: 'weight_reps' },
  { slug: 'single_leg_glute_bridge', name: 'シングルレッググルートブリッジ', category: 'glute', measurementType: 'weight_reps' },
  { slug: 'hip_thrust_machine', name: 'ヒップスラストマシン', category: 'glute', measurementType: 'weight_reps' },
  // その他
  { slug: 'foam_rolling', name: 'フォームローリング', category: 'other', measurementType: 'time' },
  { slug: 'hip_flexor_stretch', name: '股関節屈筋ストレッチ', category: 'other', measurementType: 'time' },
  { slug: 'hamstring_stretch', name: 'ハムストリングストレッチ', category: 'other', measurementType: 'time' },
  { slug: 'shoulder_stretch', name: '肩ストレッチ', category: 'other', measurementType: 'time' },
  { slug: 'cat_cow_stretch', name: 'キャットカウストレッチ', category: 'other', measurementType: 'reps' },
  { slug: 'child_pose', name: 'チャイルドポーズ', category: 'other', measurementType: 'time' },
  { slug: 'world_greatest_stretch', name: 'ワールドグレイテストストレッチ', category: 'other', measurementType: 'reps' },
  { slug: 'turkish_get_up', name: 'ターキッシュゲットアップ', category: 'other', measurementType: 'weight_reps' },
  { slug: 'medicine_ball_slam', name: 'メディシンボールスラム', category: 'other', measurementType: 'reps' },
  { slug: 'tire_flip', name: 'タイヤフリップ', category: 'other', measurementType: 'reps' },
  { slug: 'bear_crawl', name: 'ベアクロール', category: 'other', measurementType: 'time' },
  { slug: 'inchworm', name: 'インチワーム', category: 'other', measurementType: 'reps' },
  { slug: 'quad_stretch', name: '大腿四頭筋ストレッチ', category: 'other', measurementType: 'time' },
  { slug: 'calf_stretch', name: 'ふくらはぎストレッチ', category: 'other', measurementType: 'time' },
  { slug: 'chest_stretch', name: '胸ストレッチ', category: 'other', measurementType: 'time' },
  { slug: 'spinal_twist_stretch', name: '脊柱ツイストストレッチ', category: 'other', measurementType: 'time' },
  { slug: 'pigeon_pose', name: '鳩のポーズ', category: 'other', measurementType: 'time' },
  { slug: 'downward_dog', name: 'ダウンドッグ', category: 'other', measurementType: 'time' },
  { slug: 'yoga_sun_salutation', name: '太陽礼拝', category: 'other', measurementType: 'reps' },
  { slug: 'kettlebell_halo', name: 'ケトルベルハロー', category: 'other', measurementType: 'reps' },
];

export const seed = async () => {
  console.log('🌱 Seeding start...');

  try {
    const existingPresets = await db
      .select()
      .from(exercises)
      .where(eq(exercises.source, 'preset'));
    const existingBySlug = new Map(existingPresets.map((e) => [e.slug, e]));

    const now = Date.now();
    const toInsert = PRESET_EXERCISES.filter((p) => !existingBySlug.has(p.slug));
    const toUpdate = PRESET_EXERCISES.filter((p) => {
      const existing = existingBySlug.get(p.slug);
      return (
        existing !== undefined &&
        (existing.category !== p.category || existing.measurementType !== p.measurementType)
      );
    });

    if (toInsert.length > 0) {
      await db
        .insert(exercises)
        .values(toInsert.map((e) => ({ ...e, source: 'preset', createdAt: now, updatedAt: now })));
    }

    for (const p of toUpdate) {
      const existing = existingBySlug.get(p.slug)!;
      await db
        .update(exercises)
        .set({ category: p.category, measurementType: p.measurementType, updatedAt: now })
        .where(eq(exercises.id, existing.id));
    }

    console.log(`✅ exercises: +${toInsert.length} inserted, ${toUpdate.length} updated`);
  } catch (e) {
    console.error('🚨 Seeding failed', e);
  }
};
